### ISSUE TITLE
I would like to join you.

### ISSUE THREAD

**Issue by yangxyo** [EskiMojo14/keycaplendar#12]
I'm a Chinese and I'm a university student, I love to react, and new to rmwc, I find your project is a nice practice.
I want to join you, and upgrade your project to the latest version.
But I find really need a README.md ...
Or Just tell me, where I can help you.

**Comment by EskiMojo14** [comment]
Hi there!

I'm afraid this is a solo project, and I'm not looking for other contributors at the moment. 

Thank you for your interest though!
