### ISSUE TITLE
[Feature Request] Preserve filter options/preset between sessions.

### ISSUE THREAD

**Issue by pingshunhuangalex** [EskiMojo14/keycaplendar#37]
Is there a way to keep the filter options? Every time I went to the site, all filters settings are lost. Thanks.

**Comment by EskiMojo14** [comment]
Filter presets are part of the feature update I'm working on which will introduce user accounts - currently I just need to make sure that my privacy policy etc. is GDPR compliant before I feel comfortable opening these on a large scale.

See [demo](https://streamable.com/zmywaf) for how this would work.

For now, I would recommend creating a filtered URL using the filter drawer, and favouriting it.

See [demo](https://streamable.com/7xd1kx).

Hope this helps! I'll close this feature request once I've finished the accounts feature update.

**Comment by EskiMojo14** [comment]
Apologies for the delay on this, but the accounts feature update is now public - including filter presets!

Log in [here](https://keycaplendar.firebaseapp.com/login), and create presets using the filter drawer. Hopefully this should be intuitive, but feel free to let me know if you think anything can be improved.

**Comment by pingshunhuangalex** [comment]
Thanks for the updates.

The filter groups seem to work just fine. However, my filter group selection doesn't seem to be sustained with my Google account. Every time I refresh the page, it goes back to default. Just wondering if I missed anything. Please keep up the good work.

**Comment by EskiMojo14** [comment]
Ah, I see what you mean. 

Currently it doesn't store which preset you're currently using, as it would require a document write or cookie set every time you change preset. This is definitely something I'll consider changing though.

**Comment by pingshunhuangalex** [comment]
You can just quickly preserve and update it in `localStorage` if syncing it with Google account is too much of a hassle

**Comment by EskiMojo14** [comment]
> You can just quickly preserve and update it in `localStorage` if syncing it with Google account is too much of a hassle

Good point - I've been intending to use `localStorage` instead of cookies for a while.

**Comment by EskiMojo14** [comment]
After commit [6176ce](https://github.com/EskiMojo14/keycaplendar/commit/6176ce095fedf5db6ea1c475d8e2f13bd1d5e112), the site now stores your current preset ID in localStorage and reapplies it on page load after fetching the user's list of presets.

**Comment by EskiMojo14** [comment]
After #86, all filter options are preserved between sessions, regardless of if they're in a preset or not 🎉
