### ISSUE TITLE
[Feature Request] API for 3rd party app developers 

### ISSUE THREAD

**Issue by jcsumlin** [EskiMojo14/keycaplendar#39]
Hey there! Love the work yall are doing on the keycap calendar! I was wondering if you would consider making your data available via an API. I am working on a small web app for the MK community and having data on the currently running GBs would be a huge help. 
Thanks for your time and consideration,
JC

**Comment by EskiMojo14** [comment]
I think this is something that's been suggested before - having an API for keycaplendar's data would be a neat idea. Currently I have no knowledge on how to get this set up, but have added it to my Trello as an idea. Will update this if I add it 🙂

**Comment by jcsumlin** [comment]
I have experience creating expressJS apis and would love to help if I could. We can discuss details over discord if you'd like J_C___#8947

**Comment by EskiMojo14** [comment]
Implemented in #45.

**Comment by EskiMojo14** [comment]
Documentation can be found [here.](https://keycaplendar.stoplight.io/docs/keycaplendar/reference/KeycapLendar-API.v1.yaml)

In order for an app to use it, an apiKey and apiSecret must be agreed upon with myself. I am available at eskimojo#0014 on Discord, or keycaplendar@gmail.com.

As the API uses Firebase Functions and Firestore, heavy use will likely increase upkeep costs for Keycaplendar. This is something I'll have to keep an eye on.
