### ISSUE TITLE
Tooltips for the filter options?

### ISSUE THREAD

**Issue by mxmilkiib** [EskiMojo14/keycaplendar#49]
It would be handy to have, if the mouse pointer is left over a filter option, a tooltip appearing stating what the acronym stands for would be informative.

**Comment by EskiMojo14** [comment]
Hey there - each acronym is the name of the profile as assigned by the vendor/manufacturer, or the name of the manufacturer. It's not known what a lot of the acronyms stand for. 

Some are known, such as the case of GMK:
>  The name GMK is an acronym for the family names of the three original founders of the company: Güntner, Meinhardt, and Kredler. 
KAT is Keyreative All Touch, and KAM is likely something very similar.

Tracking what each acronym stands for would be inconsistent, and honestly I find it to be out of scope. Ultimately it's an arbitrary name for how the keycaps are shaped (and sometimes it implies the material they're made from).

Thanks for the idea!

**Comment by mxmilkiib** [comment]
Whilst it might not be worth creating a tool-tip for all the profile acronyms, I still hold that for some, like the shape profiles, it would be informative to allow the user to learn what they mean. Maybe even manufacturer profile acronym tooltips could even just have a quick note of their website? But no worries if this is really out of scope, thanks for the site :)
