### ISSUE TITLE
Feature Request: Favouriting an IC or GB

### ISSUE THREAD

**Issue by ben-watt-es** [EskiMojo14/keycaplendar#5]
Just the ability to favourite an interest check or group buy, to keep tabs on the ones you care about.

**Comment by EskiMojo14** [comment]
As with #4:

> This is not currently planned, as it would involve some method of tracking user data, which I'm not keen on.
> 
> I will keep this issue open as a suggestion ticket in case I change my stance on this, as it's been suggested by a few people.

**Comment by noudadrichem** [comment]
Not bashing on this. But if you're looking for this functionality, this is possible on https://keycapsets.com/

**Comment by EskiMojo14** [comment]
I've now implemented this functionality, but need to ensure that the site is GDPR compliant before I feel comfortable allowing authentication and accounts for wide use.

No current timeline for this - will do my best.

**Comment by EskiMojo14** [comment]
Apologies for the delay on this, but it's now implemented! Log in [here](https://keycaplendar.firebaseapp.com/login), and favourite a set using the heart (in card view, or in the details drawer).
