### ISSUE TITLE
Feature request: Track other MK-related stuff

### ISSUE THREAD

**Issue by pointlessone** [EskiMojo14/keycaplendar#6]
It'd be awesome to have all group buys in one place. Not only keycaps but also switches, keyboards, kits, cables, etc.

**Comment by EskiMojo14** [comment]
This has been requested a few times, but I have decided to keep keycaplendar's scope intentionally limited to keycap GBs to keep it manageable. Information regarding other areas is a lot harder to track, especially with limited quantities such as keyboards or in stock switches. Providing an end date for these would be impossible. Many keyboards are ran by the designer, and do not have a vendor in the same sense that a keycap GB would.

Tracking solely keycap GBs allows for confidence that the information provided is accurate, and doesn't overwhelm our editors with things to keep track of and update.
