### ISSUE TITLE
IC/GB for other things too?

### ISSUE THREAD

**Issue by vosechu** [EskiMojo14/keycaplendar#8]
I love that you're making this! I hope that you're able to maintain it for a while; so many burn out!

Are you parsing geekhack automatically? If so, any chance of doing cases or other things as well? I don't want to contribute to burnout, so if it's not automatic I'd hate to ask this of you (unless it's something you'd be willing to accept help with?)

**Comment by vosechu** [comment]
I see that this is a dupe of #6. Sorry about that! If having a second person updating sounds nice, let me know.

**Comment by EskiMojo14** [comment]
Thanks for the kind words! 

KeycapLendar is maintained by a small group of editors. Data entry is manual 🙂

**Comment by vosechu** [comment]
Cool, love the UI and excited to see this go forward! Let me know if you want more editors!
